export const SAVE_OFFLINE = 'SAVE_OFFLINE';
export const SAVE_PURCHASE = 'SAVE_PURCHASE';
export const SAVE_PURCHASE_START = 'SAVE_PURCHASE_START';
export const SAVE_PURCHASE_END = 'SAVE_PURCHASE_END';