export const SAVE_PURCHASE = 'SAVE_PURCHASE';
export const SAVE_PURCHASE_NEW = 'SAVE_PURCHASE_NEW';
export const SAVE_PURCHASE_NEW_START = 'SAVE_PURCHASE_NEW_START';
export const SAVE_PURCHASE_NEW_END = 'SAVE_PURCHASE_NEW_END';
export const SAVE_PURCHASE_EDIT = 'SAVE_PURCHASE_EDIT';
export const SAVE_PURCHASE_EDIT_START = 'SAVE_PURCHASE_EDIT_START';
export const SAVE_PURCHASE_EDIT_END = 'SAVE_PURCHASE_EDIT_END';